var OA_output = new Array(); 
OA_output['Sidebar 1'] = '';

OA_output['Sidebar 2'] = '';

OA_output['Sidebar 3'] = '';

OA_output['Medium Rectangle'] = '';

OA_output['Homepage prem Ad'] = '';
OA_output['Homepage prem Ad'] += "<"+"object type=\"application/x-shockwave-flash\" data=\"http://statisches.auslieferung.commindo-media-ressourcen.de/intel/INTEL_IDZ_14_07%20Q1%202-in-1%20Developer Outreach_AnimatedBanners_300X250_v3.swf?clickTag=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7291__zoneid=25__OXLCA=1__cb=26936801d1__oadest=http%3A%2F%2Fsoftware.intel.com%2Fen-us%2Farticles%2F2-in-1-user-experience%3Futm_source%3DSmashing_Magazine_Noupe%2526utm_medium%3DBanner_Ads%2526utm_campaign%3D2-in-1_UX_Campaign\" width=\"300\" height=\"250\" id=\"INTEL_IDZ_14_07 Q1 2-in-1 Developer Outreach_AnimatedBanners_300X250_v3\" style=\"float: none; vertical-align:middle;width:300px;height:250px;\">\n";
OA_output['Homepage prem Ad'] += "<"+"param name=\"movie\" value=\"INTEL_IDZ_14_07 Q1 2-in-1 Developer Outreach_AnimatedBanners_300X250_v3.swf\" />\n";
OA_output['Homepage prem Ad'] += "<"+"param name=\"quality\" value=\"high\" />\n";
OA_output['Homepage prem Ad'] += "<"+"param name=\"bgcolor\" value=\"#ffffff\" />\n";
OA_output['Homepage prem Ad'] += "<"+"param name=\"play\" value=\"true\" />\n";
OA_output['Homepage prem Ad'] += "<"+"param name=\"loop\" value=\"true\" />\n";
OA_output['Homepage prem Ad'] += "<"+"param name=\"wmode\" value=\"window\" />\n";
OA_output['Homepage prem Ad'] += "<"+"param name=\"scale\" value=\"showall\" />\n";
OA_output['Homepage prem Ad'] += "<"+"param name=\"menu\" value=\"true\" />\n";
OA_output['Homepage prem Ad'] += "<"+"param name=\"devicefont\" value=\"false\" />\n";
OA_output['Homepage prem Ad'] += "<"+"param name=\"salign\" value=\"\" />\n";
OA_output['Homepage prem Ad'] += "<"+"param name=\"allowScriptAccess\" value=\"sameDomain\" />\n";
OA_output['Homepage prem Ad'] += "<"+"a href=\"http://www.adobe.com/go/getflash\">\n";
OA_output['Homepage prem Ad'] += "<"+"img src=\"http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif\" alt=\"Get Adobe Flash player\" />\n";
OA_output['Homepage prem Ad'] += "<"+"/a>\n";
OA_output['Homepage prem Ad'] += "<"+"/object><"+"div id=\'beacon_26936801d1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7291&amp;campaignid=2708&amp;zoneid=25&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;cb=26936801d1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sidebar Special 1'] = '';

OA_output['Sidebar Special 2'] = '';

OA_output['Textad'] = '';
OA_output['Textad'] += "<"+"div id=\"textad\"><"+"script type=\'text/javascript\'><"+"!--//<"+"![CDATA[\n";
OA_output['Textad'] += "document.MAX_ct0 =\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=13bc839420__oadest=\';\n";
OA_output['Textad'] += "var m3_u = (location.protocol==\'https:\'?\'https://auslieferung.commindo-media-ressourcen.de/www/delivery/ajs.php\':\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ajs.php\');\n";
OA_output['Textad'] += "var m3_r = Math.floor(Math.random()*99999999999);\n";
OA_output['Textad'] += "if (!document.MAX_used) document.MAX_used = \',\';\n";
OA_output['Textad'] += "document.write (\"<"+"scr\"+\"ipt type=\'text/javascript\' src=\'\"+m3_u);\n";
OA_output['Textad'] += "document.write (\"?zoneid=94\");\n";
OA_output['Textad'] += "document.write (\'&amp;cb=\' + m3_r);\n";
OA_output['Textad'] += "if (document.MAX_used != \',\') document.write (\"&amp;exclude=\" + document.MAX_used);\n";
OA_output['Textad'] += "document.write (document.charset ? \'&amp;charset=\'+document.charset : (document.characterSet ? \'&amp;charset=\'+document.characterSet : \'\'));\n";
OA_output['Textad'] += "document.write (\"&amp;loc=\" + escape(window.location));\n";
OA_output['Textad'] += "if (document.referrer) document.write (\"&amp;referer=\" + escape(document.referrer));\n";
OA_output['Textad'] += "if (document.context) document.write (\"&context=\" + escape(document.context));\n";
OA_output['Textad'] += "if ((typeof(document.MAX_ct0) != \'undefined\') && (document.MAX_ct0.substring(0,4) == \'http\')) {\n";
OA_output['Textad'] += "document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));\n";
OA_output['Textad'] += "}\n";
OA_output['Textad'] += "if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");\n";
OA_output['Textad'] += "document.write (\"\'><"+"\\/scr\"+\"ipt>\");\n";
OA_output['Textad'] += "//]]>--><"+"/script><"+"noscript><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=13bc839420__oadest=http%3A%2F%2Fauslieferung.commindo-media-ressourcen.de%2Fwww%2Fdelivery%2Fck.php%3Fn%3Daf102b35%26amp%3Bcb%3D13bc839420\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/avw.php?zoneid=94&amp;cb=13bc839420&amp;n=af102b35&amp;ct0=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=13bc839420__oadest=\' border=\'0\' alt=\'\' /><"+"/a><"+"/noscript><"+"div id=\'beacon_13bc839420\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=6259&amp;campaignid=1018&amp;zoneid=68&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;cb=13bc839420\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['Comment Sponsor'] = '';
OA_output['Comment Sponsor'] += "<"+"style type=\"text/css\">\n";
OA_output['Comment Sponsor'] += "div div.singlepost.advertisement span.declare {\n";
OA_output['Comment Sponsor'] += "display: none;\n";
OA_output['Comment Sponsor'] += "}\n";
OA_output['Comment Sponsor'] += "<"+"/style><"+"style type=\"text/css\">.comment-job-board { margin: 2em 6% 2em 0; background: #FEFED3; padding: 1.25em 1em;	overflow: hidden; font: 1.2em/1.4em \"Skolar Bold\", Georgia, serif; }.comment-job-board a {display: block;color: #000;}.comment-job-board a span {padding-top:0.75em;display: block;font: 0.8em/1.4em \"Proxima Nova Regular\", Arial, sans-serif;}.comment-job-board a:focus, .comment-job-board a:active {background-color: transparent;}.comment-job-board img {float: right;margin: 0 0 0em 1em;}<"+"/style>\n";
OA_output['Comment Sponsor'] += "<"+"div class=\"comment-job-board\"><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4551__zoneid=26__OXLCA=1__cb=212ec9b8cc__oadest=http%3A%2F%2Fjobs.smashingmagazine.com%2F%3Futm_source%3Dsm%26utm_medium%3Dtextad%26utm_campaign%3Dinternal\" target=\"_self\"><"+"img src=\"http://www.smashingmagazine.com/wp-content/uploads/2012/01/job-board-transparent.gif\" style=\"border-radius: 5px; border: 1px solid rgba(0,0,0,0.05); padding: 7px; background-color: #fff; max-width: 95px !important;\" width=\"95\" />Post your job listing in our Job Board!<"+"span>If you\'re looking for a job or have a job opening to announce, post it in our job board and get noticed by professionals and well-respected companies. <"+"b style=\"text-decoration: underline;font-family: Proxima Nova Bold, Proxima Nova, Arial\">Submit a job listing<"+"/b>, and good luck!<"+"/span><"+"/a><"+"/div><"+"div id=\'beacon_212ec9b8cc\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4551&amp;campaignid=1593&amp;zoneid=26&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;cb=212ec9b8cc\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['VIS 1'] = '';

OA_output['VIS 2'] = '';

OA_output['VIS 3'] = '';

OA_output['VIS 4'] = '';

OA_output['VIS 5'] = '';

OA_output['VIS 6'] = '';

OA_output['VIS 7'] = '';

OA_output['VIS 8'] = '';

OA_output['VIS 9'] = '';

OA_output['VIS 10'] = '';

OA_output['spnsr ROS 1'] = '';
OA_output['spnsr ROS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6952__zoneid=24__OXLCA=1__cb=52e3d8ef4c__oadest=http%3A%2F%2Fwww.123rf.com%2F%3Fsrc%3Dsmashingmag%26utm_source%3DSmashingMag%26utm_medium%3DCPM%26utm_campaign%3DUS\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_v4.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'25 Million Stock Photos!\' title=\'25 Million Stock Photos!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6952__zoneid=24__OXLCA=1__cb=52e3d8ef4c__oadest=http%3A%2F%2Fwww.123rf.com%2F%3Fsrc%3Dsmashingmag%26utm_source%3DSmashingMag%26utm_medium%3DCPM%26utm_campaign%3DUS\' target=\'_blank\'>25 Million Stock Photos!<"+"/a><"+"div id=\'beacon_52e3d8ef4c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=6952&amp;campaignid=2577&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;referer=http%3A%2F%2Ft.co%2F7ah9HI4Pib&amp;cb=52e3d8ef4c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 2'] = '';
OA_output['spnsr ROS 2'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6693__zoneid=24__OXLCA=1__cb=3fa3b1e703__oadest=https%3A%2F%2Fwww.psd2html.com%2Forder-now.html%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dresponsive\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_25.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'PSD2HTML.com\' title=\'PSD2HTML.com\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6693__zoneid=24__OXLCA=1__cb=3fa3b1e703__oadest=https%3A%2F%2Fwww.psd2html.com%2Forder-now.html%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dresponsive\' target=\'_blank\'>PSD2HTML.com<"+"/a><"+"div id=\'beacon_3fa3b1e703\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=6693&amp;campaignid=2394&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;referer=http%3A%2F%2Ft.co%2F7ah9HI4Pib&amp;cb=3fa3b1e703\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 3'] = '';
OA_output['spnsr ROS 3'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7102__zoneid=24__OXLCA=1__cb=26c719d37c__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai-1b.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Online Project Management\' title=\'Online Project Management\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7102__zoneid=24__OXLCA=1__cb=26c719d37c__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'>Online Project Management<"+"/a><"+"div id=\'beacon_26c719d37c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7102&amp;campaignid=2634&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;referer=http%3A%2F%2Ft.co%2F7ah9HI4Pib&amp;cb=26c719d37c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 4'] = '';
OA_output['spnsr ROS 4'] += "<"+"script src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=rsb&c=28&pli=6080755&PluID=0&w=200&h=125&e7b8a37fd9&ncu=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5982__zoneid=24__OXLCA=1__cb=e7b8a37fd9__oadest=&wm=transparent&ucm=true\"><"+"/script>\n";
OA_output['spnsr ROS 4'] += "<"+"noscript>\n";
OA_output['spnsr ROS 4'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5982__zoneid=24__OXLCA=1__cb=e7b8a37fd9__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080755%26Page%3D%26PluID%3D0%26Pos%3D9258\" target=\"_blank\"><"+"img src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=bsr&FlightID=6080755&Page=&PluID=0&Pos=9258\" border=0 width=200 height=125><"+"/a>\n";
OA_output['spnsr ROS 4'] += "<"+"/noscript>\n";
OA_output['spnsr ROS 4'] += "<"+"br><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5982__zoneid=24__OXLCA=1__cb=e7b8a37fd9__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080749%26Page%3D%26PluID%3D0%26Pos%3D6429\" target=\"_blank\">Create free stunning sites!<"+"/a><"+"div id=\'beacon_e7b8a37fd9\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5982&amp;campaignid=130&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;cb=e7b8a37fd9\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 5'] = '';
OA_output['spnsr ROS 5'] += "<"+"script src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=rsb&c=28&pli=6080749&PluID=0&w=200&h=125&4b732497f0&ncu=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5981__zoneid=24__OXLCA=1__cb=4b732497f0__oadest=&wm=transparent&ucm=true\"><"+"/script>\n";
OA_output['spnsr ROS 5'] += "<"+"noscript>\n";
OA_output['spnsr ROS 5'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5981__zoneid=24__OXLCA=1__cb=4b732497f0__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080749%26Page%3D%26PluID%3D0%26Pos%3D928\" target=\"_blank\"><"+"img src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=bsr&FlightID=6080749&Page=&PluID=0&Pos=928\" border=0 width=200 height=125><"+"/a>\n";
OA_output['spnsr ROS 5'] += "<"+"/noscript>\n";
OA_output['spnsr ROS 5'] += "<"+"br><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5981__zoneid=24__OXLCA=1__cb=4b732497f0__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080749%26Page%3D%26PluID%3D0%26Pos%3D6429\" target=\"_blank\">Create free stunning sites!<"+"/a><"+"div id=\'beacon_4b732497f0\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5981&amp;campaignid=250&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;cb=4b732497f0\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 6'] = '';

OA_output['spnsr ROS 7'] = '';
OA_output['spnsr ROS 7'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7297__zoneid=24__OXLCA=1__cb=e44f7b5160__oadest=http%3A%2F%2Ftheme.co%2Fx%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=x-smashing.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'30+ Demos - See It Live!\' title=\'30+ Demos - See It Live!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7297__zoneid=24__OXLCA=1__cb=e44f7b5160__oadest=http%3A%2F%2Ftheme.co%2Fx%2F\' target=\'_blank\'>30+ Demos - See It Live!<"+"/a><"+"div id=\'beacon_e44f7b5160\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7297&amp;campaignid=2740&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;referer=http%3A%2F%2Ft.co%2F7ah9HI4Pib&amp;cb=e44f7b5160\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 8'] = '';

OA_output['spnsr ROS 9'] = '';

OA_output['spnsr ROS 10'] = '';
OA_output['spnsr ROS 10'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7339__zoneid=24__OXLCA=1__cb=0654859376__oadest=https%3A%2F%2Fcreativemarket.com%2Fpromocode%2Fsmashingmag15off%3Futm_source%3Dsmashingmag%26utm_medium%3Dbanner-200x125%26utm_content%3Dtemplates%26utm_campaign%3Ddiscountcode-banners-may-2014\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=templates-200x125_2.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Take 15% Off Vintage Logo Kits, Graphics, Fonts &amp; more on Creative Market\' title=\'Take 15% Off Vintage Logo Kits, Graphics, Fonts &amp; more on Creative Market\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7339__zoneid=24__OXLCA=1__cb=0654859376__oadest=https%3A%2F%2Fcreativemarket.com%2Fpromocode%2Fsmashingmag15off%3Futm_source%3Dsmashingmag%26utm_medium%3Dbanner-200x125%26utm_content%3Dtemplates%26utm_campaign%3Ddiscountcode-banners-may-2014\' target=\'_blank\'>Take 15% Off Logo Kits &amp; more<"+"/a><"+"div id=\'beacon_0654859376\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7339&amp;campaignid=2760&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;referer=http%3A%2F%2Ft.co%2F7ah9HI4Pib&amp;cb=0654859376\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 11'] = '';
OA_output['spnsr ROS 11'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7295__zoneid=24__OXLCA=1__cb=cc2e617651__oadest=http%3A%2F%2Fbit.ly%2F1kd5nGu\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=sm1_200x125_mini.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Leading Web Design Books​\' title=\'Leading Web Design Books​\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7295__zoneid=24__OXLCA=1__cb=cc2e617651__oadest=http%3A%2F%2Fbit.ly%2F1kd5nGu\' target=\'_blank\'>Leading Web Design Books​<"+"/a><"+"div id=\'beacon_cc2e617651\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7295&amp;campaignid=2738&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;referer=http%3A%2F%2Ft.co%2F7ah9HI4Pib&amp;cb=cc2e617651\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 12'] = '';
OA_output['spnsr ROS 12'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7383__zoneid=24__OXLCA=1__cb=3740c1b147__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_150.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Online Form Builder\' title=\'Online Form Builder\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7383__zoneid=24__OXLCA=1__cb=3740c1b147__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'>Online Form Builder<"+"/a><"+"div id=\'beacon_3740c1b147\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7383&amp;campaignid=2776&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;referer=http%3A%2F%2Ft.co%2F7ah9HI4Pib&amp;cb=3740c1b147\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 13'] = '';

OA_output['spnsr ROS 14'] = '';

OA_output['spnsr ROS 15'] = '';

OA_output['spnsr ROS 16'] = '';
OA_output['spnsr ROS 16'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7382__zoneid=24__OXLCA=1__cb=ce81bb7233__oadest=http%3A%2F%2Fwww.shopify.com%2Ftour%2Ffor-designers%3Futm_source%3Dsmag%26utm_medium%3Dsmag%26utm_campaign%3Ddesigners\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_149.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Shopify - ecommerce done right\' title=\'Shopify - ecommerce done right\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7382__zoneid=24__OXLCA=1__cb=ce81bb7233__oadest=http%3A%2F%2Fwww.shopify.com%2Ftour%2Ffor-designers%3Futm_source%3Dsmag%26utm_medium%3Dsmag%26utm_campaign%3Ddesigners\' target=\'_blank\'>Shopify - ecommerce done right<"+"/a><"+"div id=\'beacon_ce81bb7233\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7382&amp;campaignid=2775&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;referer=http%3A%2F%2Ft.co%2F7ah9HI4Pib&amp;cb=ce81bb7233\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 17'] = '';

OA_output['spnsr ROS 18'] = '';

OA_output['Sponsor XXL 1'] = '';
OA_output['Sponsor XXL 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7183__zoneid=77__OXLCA=1__cb=e481cf6a99__oadest=http%3A%2F%2Fwww.sitefinity.com%2Fcampaigns%2Freports%2Fforrester-report-mobile-app-or-mobile-web%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dsmmag-forrester-report\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=forresterbanner_410x125_1.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'Complimentary Forrester Report\' title=\'Complimentary Forrester Report\' border=\'0\' /><"+"/a><"+"div id=\'beacon_e481cf6a99\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7183&amp;campaignid=2686&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;referer=http%3A%2F%2Ft.co%2F7ah9HI4Pib&amp;cb=e481cf6a99\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 2'] = '';
OA_output['Sponsor XXL 2'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7184__zoneid=77__OXLCA=1__cb=74f8134529__oadest=http%3A%2F%2Fwww.sitefinity.com%2Fcampaigns%2Fsandbox%2Fdrag-and-drop-responsive-grid%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dsmmag_grid_green_banner\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=responsive-grid-smashing_magazine_2.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'Drag &amp; Drop Responsive Grid\' title=\'Drag &amp; Drop Responsive Grid\' border=\'0\' /><"+"/a><"+"div id=\'beacon_74f8134529\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7184&amp;campaignid=2687&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;referer=http%3A%2F%2Ft.co%2F7ah9HI4Pib&amp;cb=74f8134529\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 3'] = '';
OA_output['Sponsor XXL 3'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7391__zoneid=77__OXLCA=1__cb=2eefe001a1__oadest=http%3A%2F%2Fwww.godaddy.com%2Fhosting%2Fwordpress-hosting.aspx%3Fisc%3Dsmag1wpsb%26ci%3D88548%26utm_campaign%3D1_managed_wp%26utm_source%3Dsmashing_magazine%26utm_medium%3DOther%252BOnline%26utm_content%3Dsmag1wpsb%26cvosrc%3Ddisplay.smashingmagazine.bca-1160_smashing_hosting_banners_410x125\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=bca-1160_smashing_hosting_banners_410x125_copy.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_2eefe001a1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7391&amp;campaignid=2781&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2014%2F04%2F15%2Funderstanding-css-timing-functions%2F&amp;referer=http%3A%2F%2Ft.co%2F7ah9HI4Pib&amp;cb=2eefe001a1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"img src=\"http://godaddy.sp1.convertro.com/view/vt/v1/godaddy/1/cvo.gif?cvosrc=display.smashingmagazine.bca-1160_smashing_hosting_banners_410x125\" alt=\"\"/>\n";
OA_output['Sponsor XXL 4'] = '';

OA_output['Sponsor XXL 5'] = '';

